version: 0.2

phases:
    install:
        commands:
            - virtualenv node
            - . node/bin/activate
            - pip install nodeenv
            - nodeenv -p
    pre_build:
        commands:
            - npm config set user 0
            - npm config set unsafe-perm true
            - npm install @angular/cli@1.6.5
            - npm install
    build:
        commands:
            - npm run test:ci
            - npm run build:ci
    post_build:
        commands:
            - pip install awscli
            - aws s3 cp dist s3://$BUCKET/ --recursive

artifacts:
    files:
        - dist/*
