version: 0.2

phases:
    install:
        commands: 
            - virtualenv node
            - . node/bin/activate
            - pip install nodeenv
            - nodeenv -p
    pre_build:
        commands:
            - npm install @angular/cli@1.4.7
            - npm install
    build:
        commands:
            - npm run test:ci
            - ng build --target=production --environment=prod --deploy-url=https://nickplutt.com
    post_build:
        commands:
            - pip install awscli
            - aws s3 cp dist s3://$BUCKET/ --recursive

artifacts:
    files:
        - dist/*
